# 01 Extraction

In [11]:
import pandas as pd

## Shootout data

In [12]:
shootings = pd.read_csv("../Data/Raw/ShootOut_RawDataset.csv")
shootings.head()

,id,date,threat_type,flee_status,armed_with,city,county,state,latitude,longitude,location_precision,name,age,gender,race,race_source,was_mental_illness_related,body_camera,agency_ids
0,3,2015-01-02,point,not,gun,Shelton,Mason,WA,47.246826,-123.121592,not_available,Tim Elliot,53.0,male,A,not_available,True,False,73
1,4,2015-01-02,point,not,gun,Aloha,Washington,OR,45.487421,-122.891696,not_available,Lewis Lee Lembke,47.0,male,W,not_available,False,False,70
2,5,2015-01-03,move,not,unarmed,Wichita,Sedgwick,KS,37.694766,-97.280554,not_available,John Paul Quintero,23.0,male,H,not_available,False,False,238
3,8,2015-01-04,point,not,replica,San Francisco,San Francisco,CA,37.762910,-122.422001,not_available,Matthew Hoffman,32.0,male,W,not_available,True,False,196
4,9,2015-01-04,point,not,other,Evans,Weld,CO,40.383937,-104.692261,not_available,Michael Rodriguez,39.0,male,H,not_available,False,False,473

In [13]:
print('Rows:', len(shootings))
print('Columns:', len(shootings.columns))
shootings.info()

Rows: 10430
Columns: 19
<class 'pandas.DataFrame'>
RangeIndex: 10430 entries, 0 to 10429
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          10430 non-null  int64
 1   date                        10430 non-null  str
 2   threat_type                 10362 non-null  str
 3   flee_status                 8939 non-null   str
 4   armed_with                  10219 non-null  str
 5   city                        10356 non-null  str
 6   county                      5739 non-null   str
 7   state                       10430 non-null  str
 8   latitude                    9290 non-null   float64
 9   longitude                   9289 non-null   float64
 10  location_precision          9290 non-null   str
 11  name                        10112 non-null  str
 12  age                         10058 non-null  float64
 13  gender                      10410 non-null  str
 14  race                        9242 non-null   str
 15  race_source                 9264 non-null   str
 16  was_mental_illness_related  10430 non-null  bool
 17  body_camera                 10430 non-null  bool
 18  agency_ids                  10429 non-null  str
dtypes: bool(2), float64(3), int64(1), str(13)
memory usage: 1.4 MB

## Agency Data

In [14]:
agencies = pd.read_csv("../Data/Raw/Agency_RawDataset.csv")
agencies.head()

,id,name,type,state,oricodes,total_shootings
0,3145,Abbeville County Sheriff's Office,sheriff,SC,SC00100,1
1,2576,Aberdeen Police Department,local_police,WA,WA01401,1
2,2114,Abilene Police Department,local_police,TX,TX22101,8
3,2088,Abington Township Police Department,local_police,PA,PA04601,1
4,3187,Acadia Parish Sheriff's Office,sheriff,LA,LA00100,1

In [15]:
print('Rows:', len(agencies))
print('Columns:', len(agencies.columns))
agencies.info()

Rows: 3727
Columns: 6
<class 'pandas.DataFrame'>
RangeIndex: 3727 entries, 0 to 3726
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               3727 non-null   int64
 1   name             3727 non-null   str
 2   type             3726 non-null   str
 3   state            3727 non-null   str
 4   oricodes         3595 non-null   str
 5   total_shootings  3727 non-null   int64
dtypes: int64(2), str(4)
memory usage: 174.8 KB